extension/app/css/interceptor.css

fixes https://github.com/DarkFlorist/TheInterceptor/issues/9
Makes tooltips font a bit smaller and make them longer if need to be

Increase max length of tooltips and also reduce font size

---

extension/app/html/background.html
extension/app/html/changeChain.html
extension/app/html/confirmTransaction.html
extension/app/html/interceptorAccess.html
extension/app/html/personalSign.html
extension/app/html/popup.html
extension/app/manifest.json
extension/build/vendor.ts

Fixes https://github.com/DarkFlorist/TheInterceptor/issues/15
The downside of this is, that when the vendor stuff is changed, the hash changes and developer needs to remember to update the hash to `content_security_policy`. Is there a better way for this?

Fixes inline error by requiring hash and not using module type

---

extension/app/css/bulma.css

Fixes https://github.com/DarkFlorist/TheInterceptor/issues/52
Now container can resize freely without being restricted to max-widths depending on the window size

don't limit container size

---

extension/app/inpage/output/injected_document_start.js
extension/app/inpage/ts/document_start.ts
extension/app/inpage/ts/inpage.ts

- also clears the re-injection code from js side to ts
- removes `oldRequest` and `oldOn` methods away from `window.ethereum`

Refactor in page to be a class and get rid of some global variables

---

extension/app/ts/background/background.ts
extension/app/ts/background/simulationModeHanders.ts
extension/app/ts/utils/wire-types.ts

new version of https://github.com/DarkFlorist/TheInterceptor/pull/100 as the internals of RPC method parsing was changed significantly
now interceptor_getSimulationStack need to be called with version number param, like follows:
`console.log(await window.ethereum.request({ 'method': 'interceptor_getSimulationStack', 'params': ['1.0.0'] }))`
fixes https://github.com/DarkFlorist/TheInterceptor/issues/97

Add version number as mandatory field to interceptor_getSimulationStack

---

extension/app/ts/AddressBook.tsx
extension/app/ts/background/accessManagement.ts
extension/app/ts/background/background.ts
extension/app/ts/background/backgroundUtils.ts
extension/app/ts/background/metadataUtils.ts
extension/app/ts/background/windows/confirmTransaction.ts
extension/app/ts/background/windows/interceptorAccess.ts
extension/app/ts/background/windows/personalSign.ts
extension/app/ts/components/App.tsx
extension/app/ts/components/formVisualizerResults.ts
extension/app/ts/components/pages/ChangeActiveAddress.tsx
extension/app/ts/components/pages/ConfirmTransaction.tsx
extension/app/ts/components/pages/Home.tsx
extension/app/ts/components/pages/InterceptorAccess.tsx
extension/app/ts/components/pages/InterceptorAccessList.tsx
extension/app/ts/components/pages/NotificationCenter.tsx
extension/app/ts/components/pages/PersonalSign.tsx
extension/app/ts/components/simulationExplaining/SimulationSummary.tsx
extension/app/ts/components/simulationExplaining/SwapTransactions.tsx
extension/app/ts/components/simulationExplaining/Transactions.tsx
extension/app/ts/components/simulationExplaining/identifyTransaction.tsx
extension/app/ts/components/simulationExplaining/transactionExplainers.tsx
extension/app/ts/components/subcomponents/address.tsx
extension/app/ts/components/subcomponents/coins.tsx
extension/app/ts/simulation/services/LogSummarizer.ts
extension/app/ts/utils/interceptor-messages.ts
extension/app/ts/utils/user-interface-types.ts
extension/app/ts/utils/visualizer-types.ts

- gets rid of `AddressMetadata` variable type and replaces it with `AddressBookEntry` which is adressbook compatible
- In the UI code do not use `bigint` / `string`s as addresses anymore and then retrieve the name of the address from `addressMetadata` mapping, but instead move `AddressBookEntry`:s around. This enables that the UI will know where the address comes from and in the future, can rename and refer to it properly
- Instead of making big nested objects, make more flat objects with only the needed variables in them
Backgroundpage still require more refactoring to get rid of the `window.interceptor` global, but I kept that outside this PR

Big metadata refactoring

---

extension/app/ts/background/background.ts
extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts
extension/app/ts/utils/ethereum.ts
extension/test/micro-should.ts
extension/test/tests/SimulationModeEthereumClientService.ts

Fixes https://github.com/DarkFlorist/TheInterceptor/issues/84
I also checked that with these params, Ethers eRecover fails and produces error `Error: invalid point` as expected. I added test about this

Set r=0, s=0 and yParity = 'even' for simulated tx's

---

extension/app/ts/AddressBook.tsx
extension/app/ts/background/background.ts
extension/app/ts/background/popupMessageHandlers.ts
extension/app/ts/components/App.tsx
extension/app/ts/components/pages/AddNewAddress.tsx
extension/app/ts/components/pages/ConfirmTransaction.tsx
extension/app/ts/components/pages/InterceptorAccess.tsx
extension/app/ts/components/pages/PersonalSign.tsx
extension/app/ts/utils/interceptor-messages.ts
extension/app/ts/utils/user-interface-types.ts

User can rename active addresses now. When trying to rename other addresses (tokens, nft's and such) they'll get a clean error for now as renaming for those:

Utilize new AddressBookEntry type and allow renaming `addressInfo` adresses

---

extension/app/ts/background/background.ts
extension/app/ts/background/providerMessageHandlers.ts
extension/app/ts/background/simulationModeHanders.ts
extension/app/ts/background/windows/changeChain.ts
extension/app/ts/components/pages/ChangeChain.tsx
extension/app/ts/utils/interceptor-messages.ts

- Removes `window.interceptor.changeChainDialog` global
- Fixes https://github.com/DarkFlorist/TheInterceptor/issues/126
- Add `handleSigningMode` that is similar to `handleSimulationMode` to make more explicit which methods are forward and which are not. Handling these things vaguely was also one cause of #126 bug

Remove window.interceptor.changeChainDialog global. Fix chain changing bugs and add handleSigningMode

---

extension/app/ts/background/simulationModeHanders.ts
extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts
extension/app/ts/utils/constants.ts

- Fixes `eth_call` to replace missing values correctly
- If we get `'sender has deployed code'` error, retry the call with different caller (fixes issues like curve)
- If we already know common contract callers (like curve), we can just swap the address without making that additional call
- If call fails, return errors correctly and don't just return the error return value

Fixes curves issues

---

extension/app/inpage/ts/document_start.ts
extension/app/ts/background/accessManagement.ts
extension/app/ts/background/background.ts
extension/app/ts/background/iconHandler.ts
extension/app/ts/background/popupMessageHandlers.ts
extension/app/ts/background/settings.ts
extension/app/ts/background/simulationModeHanders.ts
extension/app/ts/background/windows/confirmTransaction.ts
extension/app/ts/background/windows/interceptorAccess.ts
extension/app/ts/background/windows/personalSign.ts
extension/app/ts/components/App.tsx
extension/app/ts/components/pages/ConfirmTransaction.tsx
extension/app/ts/components/pages/Home.tsx
extension/app/ts/components/pages/InterceptorAccess.tsx
extension/app/ts/components/pages/PersonalSign.tsx
extension/app/ts/listenContentScript.ts
extension/app/ts/utils/interceptor-messages.ts
extension/app/ts/utils/user-interface-types.ts

- Reconnects after service worker disconnects
- Instead of using sockets to identify connection, use connection name (generated randomly) and tab id
- Saves confirm transaction dialog information to disk so on a reconnect, so if service worker is lost when the dialog is open, we can recover
still todos: other dialogs, saving other state stuff (like simulation state)

Confirm transaction saving

---

extension/app/ts/simulation/protectors/eoaApproval.ts
extension/app/ts/simulation/protectors/eoaCalldata.ts
extension/app/ts/simulation/protectors/tokenToContract.ts
extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts

getcode was not working as ethers does not like bigints. Also protectors are now using getcode via simulation and not by directly calling the node (which was wrong if we are simulating)

Fixes getcode

---

extension/app/ts/simulation/services/EthereumClientService.ts
extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts

Fixes: https://github.com/DarkFlorist/TheInterceptor/issues/305
The bug was that the call did not work. And fetching decimals was used to fetching decimals of tokens outside our known set

Fix goerli weth decimals

---

extension/app/ts/background/iconHandler.ts

When querying for icon for tab that user has already closed results in an error, this will get rid of that error by making icon and title undefined for such page

Fix Error: No tab with id

---

extension/app/ts/components/pages/Home.tsx
extension/app/ts/components/simulationExplaining/SimulationSummary.tsx
extension/app/ts/components/simulationExplaining/SwapTransactions.tsx
extension/app/ts/components/simulationExplaining/Transactions.tsx
extension/app/ts/utils/user-interface-types.ts

Fix https://github.com/DarkFlorist/TheInterceptor/issues/243
I moved reset button higher, where it makes more sense, and renamed it to `clear` instead, that sounds more clear (no pun intended)

make removing transactions fast, disable reset on click

---

extension/app/ts/background/popupMessageHandlers.ts
extension/app/ts/background/settings.ts
extension/app/ts/utils/wire-types.ts

Fix: https://github.com/DarkFlorist/TheInterceptor/issues/337
as we cannot store undefines to the storage, store account as "missing" string instead

Fix account unavailable by being able to store undefined

---

extension/app/ts/background/background.ts
extension/app/ts/background/backgroundUtils.ts
extension/app/ts/background/popupMessageHandlers.ts
extension/app/ts/background/windows/confirmTransaction.ts
extension/app/ts/components/App.tsx
extension/app/ts/components/pages/ConfirmTransaction.tsx
extension/app/ts/components/pages/Home.tsx
extension/app/ts/components/subcomponents/DinoSays.tsx
extension/app/ts/utils/errors.ts
extension/app/ts/utils/interceptor-messages.ts

Work towards https://github.com/DarkFlorist/TheInterceptor/issues/335
- Now if you lose connection when forming transaction you get an error and forming transaction is retryed when new block arrives
- Show error on simulation stack too if we cannot update it
still todo:
1) If dapp queries the extension we don't manage the error nicely
2) we should change our icon as not connected if no connection

confirm transaction and simulation state connection errors

---

extension/app/ts/background/simulationModeHanders.ts
extension/app/ts/background/windows/changeChain.ts

Fixes #347 
When `onCloseWindow` is called, it checks the closed window in event is the same  window.id and then sets `openedWindow = null`
On the finally block during cleanup, the onCloseWindow listener is removed before the popup event comes in.

Fix race condition, close popup listener is removed before event

---

extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts

ethers throw:
`RangeError: data out-of-bounds (buffer=0x, length=0, offset=32, code=BUFFER_OVERRUN, version=6.1.0)`
when `data` is empty

When log does not match what we expect, ethers can throw instead of returning null

---

.gitignore
app/css/interceptor.css
app/ts/background/windows/personalSign.ts
app/ts/components/pages/PersonalSign.tsx
app/ts/utils/eip712Parsing.ts
app/ts/utils/personal-message-definitions.ts
app/ts/utils/wire-types.ts
test/tests/signTypedData.ts

- parses message field: checks that the type information is available and then add address metadata to it.
- Visualize arbitrary EIP-712 messages
- This only applies o EIP-712 messages that we do not directly recognize
- Does not include domain fields parsing, I added issue about it (https://github.com/DarkFlorist/TheInterceptor/issues/404)

Parse and validate EIP-712 messages and show metadata on them

---

app/ts/utils/constants.ts

Fix https://github.com/DarkFlorist/TheInterceptor/issues/467
Other option is just call it "Transfer From" but I am not sure if "ERC20/ERC721 Transfer From" is more clear

add ERC721 to fourbyte explanation for Transfer Form

---

app/manifestV2.json

I guess that WASN'T the id....... it requires brackets

Requires brackets when using UUID in manifest mozilla id

---

app/ts/background/accessManagement.ts
app/ts/background/background.ts
app/ts/background/backgroundUtils.ts
app/ts/background/iconHandler.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/providerMessageHandlers.ts
app/ts/background/settings.ts
app/ts/background/simulationModeHanders.ts
app/ts/background/storageVariables.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/background/windows/interceptorAccess.ts
app/ts/background/windows/personalSign.ts
app/ts/components/App.tsx
app/ts/utils/interceptor-messages.ts

Currently interceptor forces signer to only have one address active at a time (and when this is not the case, interceptor behaves bit weirdly).
This change makes it so that every tab can have their own signer account.
This change also makes access management a bit simpler, now access is checked at the beginning of the RPC query and the active address doesn't change during lifespan of the request
Should fix https://github.com/DarkFlorist/TheInterceptor/issues/484

Allow each tab have their own signer account

---

app/inpage/ts/inpage.ts
app/ts/AddressBook.tsx
app/ts/background/accessManagement.ts
app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/providerMessageHandlers.ts
app/ts/background/simulationModeHanders.ts
app/ts/background/storageVariables.ts
app/ts/background/windows/changeChain.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/background/windows/interceptorAccess.ts
app/ts/background/windows/personalSign.ts
app/ts/components/App.tsx
app/ts/components/pages/AddNewAddress.tsx
app/ts/components/pages/ChangeChain.tsx
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/pages/Home.tsx
app/ts/components/pages/InterceptorAccess.tsx
app/ts/components/pages/InterceptorAccessList.tsx
app/ts/components/pages/PersonalSign.tsx
app/ts/simulation/services/EthereumSubscriptionService.ts
app/ts/simulation/services/SimulationModeEthereumClientService.ts
app/ts/utils/interceptor-messages.ts
app/ts/utils/wire-types.ts

- fix https://github.com/DarkFlorist/TheInterceptor/issues/519
- refactor:
- RPC return values are now type checked and serialized at the end
- rename "options" field to "data", as they weren't really options
- unify RPC handling of simulation and signing mode to one function instead of two (as we now pass almost everything via our node)
- use readonly tuples instead of tuples

Use interceptors rpc when possible

---

app/ts/background/storageVariables.ts
app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx
app/ts/components/simulationExplaining/identifyTransaction.tsx

There was a bug in identifying a simple transfer. This is what the view should look like:
When a transfer is identified but it's not a simple transfer, we fallback to show the transfer anyway, I added recipient to this as well:
Previous storage changes also break the old storage, so I made it so that those storage variables are just cleared (it clears pending transactions if they exist) if parsin fails and issues a warning.
Fix https://github.com/DarkFlorist/TheInterceptor/issues/482

show recipient on token transfer and when pending transactions are corrupt clear them

---

app/html/background.html
app/manifestV2.json
app/ts/background/accessManagement.ts
app/ts/background/background-startup.ts
app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/providerMessageHandlers.ts
app/ts/background/simulationModeHanders.ts
app/ts/background/storageVariables.ts
app/ts/background/windows/changeChain.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/background/windows/interceptorAccess.ts
app/ts/backgroundServiceWorker.ts
app/ts/components/App.tsx
app/ts/components/pages/Home.tsx
app/ts/simulation/services/EthereumClientService.ts
app/ts/simulation/simulator.ts
app/ts/utils/interceptor-messages.ts
app/ts/utils/user-interface-types.ts
app/ts/utils/visualizer-types.ts

- many popups were calling `background.js` which resulted `startup()` function being called for popups, which is a function that should only be called when interceptor starts. This resulted in us having multiple simulation states that sometimes got synced back together. I separated these startup functions to a separate file (background-startup.js) and made simulator variable a const that is moved around instead of being a global variable
- blur now only happens when the simulation state is clearly wrong (user has changed their active address, user has changed get rich mode or user has changed network)

Separate startup script

---

app/ts/background/storageVariables.ts
app/ts/background/windows/changeChain.ts
app/ts/background/windows/interceptorAccess.ts
app/ts/background/windows/personalSign.ts
app/ts/components/ui-utils.tsx

The ens site is calling eth_requestAccounts in a loop all the time and this caused interceptor to behave badly. Now if dapp requests this account, we throw `Access request pending already` error. 
There was also another race condition bug caused by this, when you approve the request, it takes couple frames for access rights to propagate and during this time the dapp requested access again while the accesses were already.
And there's a third bug, I did not know tabs `id` and `windowId` are separate things, so now I am just using `id` to track things, instead of both mixed. 
fix https://github.com/DarkFlorist/TheInterceptor/issues/591

Don't prompt access request again for the same request

---

app/ts/components/pages/ConfirmTransaction.tsx

Found this when trying to submit raw signed txs. I'm assuming network name is the best option to display to users? RPC URL would give potentially better insight for advanced users but different custom networks added should be named appropriately by users anyway.

Confirm Dialouge crashes when trying to cast rpcNetwork object as string

---

app/ts/background/background.ts
app/ts/utils/JsonRpc-types.ts
app/ts/utils/interceptor-messages.ts

- forward `wallet_addEthereumChain` to wallet
- forward all unknown json rpc methods to a wallet that we are not supporting. This is done so that we are checking that the method is not one we support, and only then forward. If the dapp is sending a request method that we support, but with invalid parameters, we will block it and throw error
fix https://github.com/DarkFlorist/TheInterceptor/issues/569

Support for unsupported methods

---

app/inpage/ts/inpage.ts
app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/simulationModeHanders.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/components/App.tsx
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/simulationExplaining/SimulationSummary.tsx
app/ts/simulation/services/SimulationModeEthereumClientService.ts
app/ts/utils/JsonRpc-types.ts
app/ts/utils/interceptor-messages.ts
app/ts/utils/visualizer-types.ts
test/tests/nethermindComparison.ts

- partially fixes https://github.com/DarkFlorist/TheInterceptor/issues/602 in a way that if when a new block is confirmed, the nonce is checked. However, we are not still counting pending transactions, only confirmed ones
- makes sure that error's data object is propagated to the dapp if available
-fix https://github.com/DarkFlorist/TheInterceptor/issues/606 :

Transaction sending rework

---

app/ts/background/background-startup.ts

with this change, if you run
```
await window.ethereum.request({
"method":"eth_requestAccounts",
"params":[{ }]
})
```
on console on this site (while in signing mode), we first request access to the site, then ask signer for the address and then request access with that address.
Before we just denied access to the site as metamask was not giving address to us

fix asking access on non-signer connected sites

---

app/ts/simulation/services/SimulationModeEthereumClientService.ts

when calculating the nonce for multicall for `eth_call`, if eth_call's from field matched to some simulation stacks transation, that resulted in a nonce error as we are using wrong block tag.

fix wrong nonce on eth_call

---

app/ts/background/settings.ts
app/ts/background/storageVariables.ts
app/ts/utils/storageUtils.ts

fix https://github.com/DarkFlorist/TheInterceptor/issues/597
- gets rid of wrong type casting `as string`
- gets rid of doing parsing and serializing separately and instead do it in one place

refactor local storage functions

---

app/ts/background/settings.ts
app/ts/utils/storageUtils.ts

`exportSettingsAndAddressBook` was parsing settings from local storage twice and failing when trying to parse address twice as it gets converted to bigint

Parse exported settings only once

---

app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/pages/InterceptorAccess.tsx

fix errors: "Unchecked runtime.lastError: No tab with id: 942650812." when we try to reach for tab id that has been closed

catch tab id errors and ignore them

---

app/ts/AddressBook.tsx
app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/components/App.tsx
app/ts/components/pages/AddNewAddress.tsx
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/pages/InterceptorAccess.tsx
app/ts/components/pages/PersonalSign.tsx
app/ts/simulation/services/EtherScanAbiFetcher.ts
app/ts/types/addressBookTypes.ts
app/ts/types/etherscan.ts
app/ts/types/interceptor-messages.ts

Fixes  partially https://github.com/DarkFlorist/TheInterceptor/issues/706
- Adds button to import ABI from etherscan
- ABI is saved to addressbook
still missing that user could see the abi somewhere and that user could paste the abi themselves (we need verification for this), and user should be able to change eherscan api key

Retrieve ABI from etherscan

---

app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/storageVariables.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/types/JsonRpc-types.ts
app/ts/types/accessRequest.ts
app/ts/types/visualizer-types.ts
app/ts/utils/typed-arrays.ts

Open Confirm transaction dialog faster by:
- Not waiting for nonce calculation
- Not waiting for gas limit calculation
- Not waiting for simulation to finish
Update these values after dialog has been opened afterwards

Open confirm transaction view faster

---

app/ts/components/subcomponents/Hint.tsx

The MouseEvent property `event.pageY` takes into account the position of the mouse at the time of the event relative to the document (globalThis) thus will be off positioned when the document is scrolled. This change just replaced the property being tracked to `event.clientY` to track the event relative to the viewport.
Fixes #764

Fix tooltip being off-positioned when page is scrolled

---

app/ts/simulation/protectors/tokenToContract.ts

the check for sending tokens to a contract was complaining about tokens address, while it should complain about the target contract

do not show token contract, but the receiving contract

---

app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx

Also does a minor refactor for pluralization that I believe makes it a bit more readable.
The main purpose of this change is to fix `log => event`.  If you dislike the refactor I did, I don't mind backing it out.  I was confused when I first read the code due to the ternary, so I figured I would change it to what I *expected* to help the next reader.

Change `log` to `event`.

---

app/inpage/ts/inpage.ts
app/ts/background/accessManagement.ts
app/ts/background/background-startup.ts
app/ts/background/background.ts
app/ts/background/messageSending.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/providerMessageHandlers.ts
app/ts/background/simulationModeHanders.ts
app/ts/background/windows/changeChain.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/background/windows/interceptorAccess.ts
app/ts/background/windows/personalSign.ts
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/simulation/services/EthereumSubscriptionService.ts
app/ts/types/interceptor-messages.ts

- Refactor confirm transaction so that we do not wait for a promise anymore, but resolve the transactions from the local storage always
- When forward to signer request is sent to a signer, get the signers reply back to the interceptor and then return it only after that (currently we just log that this happened, but we don't do any modifications to it)
- Add `type` variable to forwarding messages to make it more clear what kind of message it is. Before there was quite confusing way to recognize it
work towards https://github.com/DarkFlorist/TheInterceptor/issues/810

Refactor confirm transaction

---

app/inpage/ts/inpage.ts
app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts
app/ts/background/providerMessageHandlers.ts
app/ts/background/storageVariables.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/subcomponents/Spinner.tsx
app/ts/types/accessRequest.ts
app/ts/types/interceptor-messages.ts

when sending transaction on signing mode, don't close the window but go into pending mode and close the window only when signer has approved it. If signer throws error, show that error on the UI

keep window open when sending transaction on signing mode until its approved by signer

---

app/ts/background/popupMessageHandlers.ts

fixes an issue caused by https://github.com/DarkFlorist/TheInterceptor/pull/882 . Where if you updated metadata (egg accounts name) in personal sign dialog, it would not update.

update message sign metadata when user changes metadata

---

app/inpage/ts/inpage.ts
app/ts/background/background.ts
app/ts/background/providerMessageHandlers.ts
app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx
app/ts/simulation/services/SimulationModeEthereumClientService.ts
app/ts/types/JsonRpc-types.ts
app/ts/types/interceptor-messages.ts
app/ts/utils/ethereum.ts

- calculate contract deployment address and show it in UI
- add right contract deployment address to transaction receipt
- don't require `maxPriorityFeePerGas` if `maxFeePerGas` is set

remix fixes

---

app/inpage/ts/inpage.ts

Interceptor Icon should also adapt to browser default text color with `fill=currentColor` so it would appear black on most light themed websites, and white on dark themed websites

Fix Interceptor Icon to be Data URI Encoded

---

app/ts/components/subcomponents/SVGBlockie.tsx

Force renderer (browser) to display this SVG in crisp edges.
Update:
- preact doesn't actually transform the camelCase attribute so used dashes

Fix blockie rendering gaps

---

app/ts/types/wire-types.ts
test/tests/nethermindComparison.ts

the blockheader can be null if its missing: <https://www.quicknode.com/docs/ethereum/eth_getBlockByNumber>

blockheader can be null

---

app/ts/background/background.ts
app/ts/background/metadataUtils.ts
app/ts/background/popupMessageHandlers.ts
app/ts/components/formVisualizerResults.ts
app/ts/simulation/logHandlers.ts
app/ts/simulation/simulator.ts
app/ts/types/visualizer-types.ts
app/ts/utils/bigint.ts
app/ts/utils/constants.ts
app/ts/utils/ethereumNameService.ts

- when doing ENS name resolutions, add all addresses in the stack and calculate reverse hashes and check if any nodes matches to those. If a math is found cache is for future use
- name changed event
- reverse claimed event

reverse resolution hashes

---

app/css/bulma.css
app/css/interceptor.css
app/ts/components/simulationExplaining/SimulationSummary.tsx

Updated the layout of raw transaction for data value to be closer to it's label and with more prominent colors. Pre-formatted data (raw) will also start using the new legible font
| <img width="496" alt="Screenshot 2024-06-21 at 10 40 50 AM" src="https://github.com/DarkFlorist/TheInterceptor/assets/1169838/83903064-9673-4db9-bf54-63a471be03f3"> | <img width="498" alt="Screenshot 2024-06-21 at 10 46 02 AM" src="https://github.com/DarkFlorist/TheInterceptor/assets/1169838/5186dc22-9078-4f2e-8bab-4b4418768fa0"> |
|:--:|:--:|
|_new_|_existing_|

Re-layout Raw Transaction Information

---

app/ts/components/simulationExplaining/SimulationSummary.tsx
app/ts/components/subcomponents/coins.tsx

if there's no price estimate, this shows `( )`. Nowadays we just leave it out

empty parentheses for price

---

app/ts/components/simulationExplaining/SimulationSummary.tsx
app/ts/components/subcomponents/coins.tsx

- add space between number and token symbol in token price
- in raw transaction view, don't show some values in gray

add space between number and token symbol in token price

---

app/ts/background/medataSearch.ts

Fix Addressbook search error on special character input

---

Dockerfile

This is to resolve the issue reported that Firefox failed to load fonts logged as
```
downloadable font: download failed (font-family: "Inter" style:normal weight:100..900 stretch:100 src index:0): status=2152857621 source: moz-extension://9c1d476d-b11a-4116-b8c3-9b7418c7b4fc/fonts/InterVariable.woff2
downloadable font: download failed (font-family: "Atkinson" style:normal weight:400 stretch:100 src index:0): status=2152857621 source: moz-extension://9c1d476d-b11a-4116-b8c3-9b7418c7b4fc/fonts/Atkinson-Hyperlegible-Regular-102a.woff2 
```

Add fonts in build

---

.github/workflows/release-extension.yml

v4 download-artifacts is incompatible with v3 upload-artifacts.

Updates upload-artifacts to latest.

---

app/css/interceptor.css

Unclosed stylesheet statement would cause succeeding CSS declarations not to work properly

Fix invalid CSS syntax

---

app/ts/components/subcomponents/InlineCard.tsx
app/ts/components/subcomponents/coins.tsx

Replaced Eth symbol to use UI same with address
| <img width="287" alt="Screenshot 2024-10-22 at 1 53 08 PM" src="https://github.com/user-attachments/assets/78733a74-36b8-4780-b626-83a6d54eaa73"> | <img width="287" alt="Screenshot 2024-10-22 at 1 52 56 PM" src="https://github.com/user-attachments/assets/5db2e46b-cc51-4b17-8914-829b373950a5"> |
|--|--|
New Feature:

Replace ETH UI with Inline Card

---

app/ts/background/background-startup.ts
app/ts/background/background.ts
app/ts/background/windows/confirmTransaction.ts
app/ts/components/App.tsx
app/ts/simulation/compoundGovernanceFaking.ts
app/ts/simulation/services/EthereumClientService.ts
app/ts/simulation/services/EthereumSubscriptionService.ts
app/ts/simulation/services/SimulationModeEthereumClientService.ts
app/ts/types/wire-types.ts
test/tests/nethermindComparison.ts

- fix bug that we are querying block number +1 while we should query the current block number.
- Handle case where the RPC returns NULL as the block

handle null getblock return

---

app/ts/simulation/services/EthereumClientService.ts
app/ts/utils/constants.ts

- fix https://github.com/DarkFlorist/TheInterceptor/issues/1153
- make the cache 5 blocks instead of 100. This means that if we notice the cache is older than 5 blocks, we don't use it anymore. This happens when interceptor has went to sleep and the user returns to do stuff, then while interceptor is retrieving the new block, we might use older blocks up to 5.

block cache constant

---

app/ts/components/subcomponents/coins.tsx

Adjusted text alignment of numbers to baseline text. Fixes #1166 
| <img width="161" alt="Screenshot 2024-10-29 at 1 46 33 PM" src="https://github.com/user-attachments/assets/826d654a-bc5f-4c54-8b5c-2dec1bf1b72d"> | <img width="202" alt="Screenshot 2024-10-29 at 1 46 04 PM" src="https://github.com/user-attachments/assets/e9e18052-d01b-49bb-ba04-495a783559d7"> |
|--|--|
- Add CSS property type and use JS notation for completion

Align zero prefix numbers to bottom of text

---

app/ts/background/medataSearch.ts

there's a bug that interceptor complains about duplicate address when we are on different chain than mainnet

don't check duplicates from dark florist metadata unless we are on chain 1 or allchains

---

app/ts/background/storageVariables.ts

If the user has vitalik as onchain entry and as user added entry, currently the onchain entry is shown, which is wrong. This reverses this

prioritize users entries over onchain entries

---

app/ts/components/pages/SettingsView.tsx
app/ts/components/subcomponents/ConfigureRpcConnection.tsx

fix https://github.com/DarkFlorist/TheInterceptor/issues/1189

custom blockexplorer

---

app/ts/components/pages/ConfirmTransaction.tsx

- there's a bug that when as a user you try to force send transaction that is failing, interceptor doesn't let you as `useComputed` doesn't update the buttons disabled state

remove use states from confirmTransaction

---

app/ts/components/pages/WebsiteAccess.tsx

This message should only be shown if user denied interceptor access to the website and is currently shown by default in #1221 
| <img width="526" alt="Screenshot 2024-12-10 at 11 01 40 AM" src="https://github.com/user-attachments/assets/d5d42b4f-0155-4e95-8982-1c0cde864139"> |
|:--:|
| _No access prompt_ |

Only show "No access" message for user-denied sites

---

app/ts/components/pages/WebsiteAccess.tsx
app/ts/utils/OptionalSignal.ts

- Replace form logic which simple state change as form submit did not work (it seems to return old value and lag behind one selection)
- clean up with optional signal

clean up & fix issue with form submit returning old value

---

app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/simulationExplaining/SimulationSummary.tsx

When the window is small.
Instead of showing:
show:

show gas fee line better

---

app/ts/AddressBook.tsx
app/ts/components/App.tsx
app/ts/components/pages/AddNewAddress.tsx
app/ts/components/pages/ConfirmTransaction.tsx
app/ts/components/pages/Home.tsx
app/ts/components/pages/InterceptorAccess.tsx
app/ts/components/pages/InterceptorAccessList.tsx
app/ts/components/pages/WebsiteAccess.tsx
app/ts/types/user-interface-types.ts
app/ts/types/websiteAccessTypes.ts

- fix https://github.com/DarkFlorist/TheInterceptor/issues/1131
- fix address renaming. There's couple bugs in address renaming:
-> we are modifying readonly signal
-> when etherscan abi is retrieved and there's no abi, the error just blinks as there's a loop to clear it
-> address renaming code is also a bit mess, and now its nicer as we modify signals instead of always looping around background page

add rename to website access and fix renaming

---

app/ts/background/background.ts
app/ts/background/popupMessageHandlers.ts

- When user flips the richmode, don't reset simulation, but instead just remove it from the current simulation and refresh

don't reset simulation when flipping rich switch

---

app/ts/components/simulationExplaining/identifyTransaction.tsx

- fixes a bug that initial report is considered as proxy transfer on Augur

if no direct path is found, do not consider it a proxy transfer

---

app/ts/background/windows/personalSign.ts
app/ts/utils/eip712.ts

the try catch is unnecessary nowadays as we are checking above already if its valid eip712 message and if its not, we return

remove unnecessary try catch

---

app/ts/background/popupMessageHandlers.ts
app/ts/simulation/services/EthereumClientService.ts
app/ts/simulation/services/EthereumJSONRpcRequestHandler.ts
app/ts/simulation/services/SimulationModeEthereumClientService.ts

- Fixed: if you make duplicated rpc calls, and the call fails, the duplicated promises never get rejected
- Fixed: If a new block arrives when new transaction is being refreshed, undefined error is thrown
- Fixed: if get code call fails, return error to UI instead showing undefined error

error handling fixes
