extension/package.json, readme.md
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/22
=> add -ignore-scripts flag and remove addressData command as its no longer used

extension/app/inpage/output/injected_document_start.js, extension/app/inpage/ts/document_start.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/17
=> Silence "Extension context invalidated" -error

extension/app/inpage/output/injected_document_start.js, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/simulation/protectors/commonTokenOops.ts
- Display highlighted token transfers receiving address correctly
- Fix common token oops to use tokens destination address and not the tokens address
- Forgotten .js file update from previous PR
=> Fix token transfers (oops and destination addr)

extension/app/ts/background/settings.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/40
=> default to poor Vitalik

extension/app/html/background.html, extension/app/html/changeChain.html, extension/app/html/confirmTransaction.html, extension/app/html/interceptorAccess.html, extension/app/html/personalSign.html, extension/app/html/popup.html, extension/app/manifest.json, extension/build/vendor.ts, extension/package-lock.json, extension/package.json
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/54 , (thank you @DecentralisedTech!)
- workaround for issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1803984
- Remove ES shims
=> remove shims and fix firefoxes issue

extension/app/ts/components/pages/ChangeActiveAddress.tsx, extension/app/ts/components/subcomponents/address.tsx
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/65
=> Fix UI problem of change active address

extension/app/ts/simulation/protectors/eoaApproval.ts, extension/app/ts/utils/calldata.ts
Fixes: https://github.com/DarkFlorist/TheInterceptor/issues/49
=> Allow approval of 0 for EOA

extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/subcomponents/address.tsx
=> Fix addresses going into multiple line in addressbook

extension/app/ts/background/background.ts, extension/app/ts/background/iconHandler.ts, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/subcomponents/CopyToClipboard.tsx, extension/app/ts/components/subcomponents/Hint.tsx, extension/app/ts/components/subcomponents/SomeTimeAgo.tsx, extension/app/ts/components/subcomponents/signers.tsx, extension/app/ts/utils/constants.ts, extension/app/ts/utils/user-interface-types.ts
fixes: https://github.com/DarkFlorist/TheInterceptor/issues/31
=> Explain interceptor icon on mouse over

extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/transactionExplainers.tsx
=> Do not show eth donator losing funds anymore. Fix the look of make you rich tx (it seemed to have broken by previous changes)

extension/app/ts/background/metadataUtils.ts, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/utils/visualizer-types.ts, extension/package-lock.json, extension/package.json
For mozilla add-on < 4MB file limit
=> Integrate address-metadata with segregated json

extension/app/css/bulma.css, extension/app/css/interceptor.css, extension/app/img/rename.svg, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/ChangeActiveAddress.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/pages/NotificationCenter.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/subcomponents/RenameAddressButton.tsx, extension/app/ts/components/subcomponents/address.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/utils/user-interface-types.ts, extension/app/ts/utils/visualizer-types.ts
Add edit address button to the main popup window (you cannot yet edit addresses on other popups, they require some more work)
The edit button is hidden and shows up on mouse over
=> Add edit address button to the popup window

extension/app/ts/AddressBook.tsx, extension/app/ts/background/medataSearch.ts, extension/app/ts/background/metadataUtils.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/components/subcomponents/DataURLCache.ts, extension/app/ts/components/subcomponents/PreactBlocky.tsx, extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/typed-arrays.ts
=> Add search and paging to addressbook

extension/app/css/interceptor.css, extension/app/ts/AddressBook.tsx, extension/app/ts/background/background.ts, extension/app/ts/background/metadataUtils.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/AddressList.tsx, extension/app/ts/components/pages/ChangeActiveAddress.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/components/subcomponents/address.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/visualizer-types.ts, extension/app/ts/utils/wire-types.ts
Allows creating new active addresses and removing them in address book. Also styles address book elements and fixes logoUri issue that was caused by update to the ne addressmetadata version.
=> addressbook: create/delete addresses, logoURI issue, addressbookStyling

extension/app/ts/components/pages/Home.tsx
=> Adds padding before make-me-rich checkbox

extension/app/css/interceptor.css, extension/app/ts/AddressBook.tsx, extension/app/ts/background/medataSearch.ts, extension/app/ts/background/metadataUtils.ts
- Makes modal dialogs take at max 90% of the space, instead of always taking that much
- Refactor `getFullLogoUri` calculation behind one function instead of repeating it everywhere where address metadata was used
- Disable most of the buttons that do not work yet (like adding new tokens, removing tokens and such)
- Add edit button. Before the plan was that the user would edit the list directly, but I think it more clear when user clicks the edit button to do edits
=> Addressbook improvements

extension/app/ts/components/subcomponents/PreactBlocky.tsx, extension/app/ts/components/subcomponents/address.tsx
there's a bug now where if you switch address, the blocky does not change, this fixes it
=> Fix bug causing blocky to not refresh on address change

extension/app/ts/background/settings.ts, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/utils/constants.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/117
=> Add 0x1 privatekeys address as second default address and allow signing with it

extension/app/ts/AddressBook.tsx
fixes https://github.com/DarkFlorist/TheInterceptor/issues/123
=> Allow users to copy addresses in address book

extension/app/html/addressBook.html, extension/app/html/changeChain.html, extension/app/html/confirmTransaction.html, extension/app/html/interceptorAccess.html, extension/app/html/personalSign.html, extension/app/html/popup.html, extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/settings.ts, extension/app/ts/components/App.tsx, extension/app/ts/utils/interceptor-messages.ts
No when you attempt to open address book and you have it open already, Interceptor will activate that tab instead of opening a new one
=> Activate old address book if it's already open, add title to all html pages

extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/utils/wire-types.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/142
=> Adds pending

extension/app/ts/AddressBook.tsx, extension/app/ts/background/backgroundUtils.ts, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/ChangeChain.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/pages/NotificationCenter.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx
wraps `browser.runtime.sendMessage` with `sendPopupMessageToBackgroundPage` to make sure the type is correct for messages
=> Add sendPopupMessageToBackgroundPage to benefit from type safety of messages

extension/app/ts/components/pages/AddNewAddress.tsx
=> Fix adding new addr

extension/app/ts/AddressBook.tsx, extension/app/ts/background/accessManagement.ts, extension/app/ts/background/background.ts, extension/app/ts/background/iconHandler.ts, extension/app/ts/background/medataSearch.ts, extension/app/ts/background/metadataUtils.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/settings.ts, extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/background/windows/personalSign.ts, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/utils/interceptor-messages.ts
=> Contacts now working

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/background/windows/confirmTransaction.ts, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/utils/interceptor-messages.ts
This allows to show user which website is requesting the transaction
Work towards https://github.com/DarkFlorist/TheInterceptor/issues/139
=> Bring website origin and icon to confirm tx dialog

extension/app/css/interceptor.css, extension/app/ts/AddressBook.tsx, extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/background/windows/confirmTransaction.ts, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx, extension/app/ts/components/simulationExplaining/transactionExplainers.tsx, extension/app/ts/components/subcomponents/Error.tsx, extension/app/ts/components/subcomponents/Hint.tsx, extension/app/ts/components/subcomponents/address.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/components/ui-utils.ts, extension/app/ts/utils/user-interface-types.ts, extension/app/ts/utils/visualizer-types.ts
- Gets rid of refresh button (but there's no auto refresh added this is a todo)
- shows website in confirm transaction / homepage, on homepage I am just showing a mockup, this is also a TODO as we are not storing the website that made the transaction atm
- approvals / sending tokens don't look good atm, and also need to be reworked
- Fixes https://github.com/DarkFlorist/TheInterceptor/issues/104
=> Confirm transaction and home pages transaction view UI rewamp

extension/app/css/interceptor.css, extension/app/ts/background/accessManagement.ts, extension/app/ts/background/background.ts, extension/app/ts/background/backgroundUtils.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/providerMessageHandlers.ts, extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/subcomponents/DinoSays.tsx, extension/app/ts/components/subcomponents/address.tsx, extension/app/ts/utils/interceptor-messages.ts
- Fixes https://github.com/DarkFlorist/TheInterceptor/issues/24
- Also redesigns request dialog to align the new style
Adds address change button on simulation mode:
And a refresh button on signer mode:
=> Change address on access request dialog

extension/app/ts/background/background.ts, extension/app/ts/components/pages/ConfirmTransaction.tsx
Now when a new block arrives, the simulation is refreshed on both confirmation window and in the home page
=> Auto refresh simulations

extension/app/css/interceptor.css, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx
=> unify importance box, split different events on importance box into multiple lines

extension/app/css/bulma.css, extension/app/css/interceptor.css, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/simulationExplaining/EtherTransferVisualisation.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx
Fix: https://github.com/DarkFlorist/TheInterceptor/issues/188
=> Sending ether visualisation

extension/app/ts/components/subcomponents/PreactBlocky.tsx, extension/app/ts/components/subcomponents/coins.tsx
=> fix blocky tokens aligment

extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx
Work towards https://github.com/DarkFlorist/TheInterceptor/issues/190
=> Identify approval

extension/app/inpage/output/injected_document_start.js, extension/app/inpage/ts/inpage.ts
=> Throw error on unsupported methods

extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, extension/app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx
fixes https://github.com/DarkFlorist/TheInterceptor/issues/190
=> Simple token approval UI

extension/app/ts/AddressBook.tsx, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/components/pages/ChangeChain.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/utils/interceptor-messages.ts
Fixes issue that interceptor breaks when an interceptor window is open and you change between simulation / signing mode
=> Fix not parsing all possible received messages in popups

extension/app/ts/components/App.tsx, extension/app/ts/components/pages/NotificationCenter.tsx, extension/app/ts/utils/user-interface-types.ts
Slowly working towards https://github.com/DarkFlorist/TheInterceptor/issues/210
=> get rid of last browser.runtime.getBackgroundPage()

extension/app/css/interceptor.css, extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx
Fix bug when access rights update in middle of users editing process causing user to lose the changes on access rights
=> Fix refresh bug in accesslist

extension/app/ts/components/pages/InterceptorAccessList.tsx
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/228
=> Fixes access rights getting out of sync if you modify access rights on a popup at the same time with having them open at the same time

extension/app/ts/background/metadataUtils.ts, extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/pages/NotificationCenter.tsx, extension/app/ts/components/subcomponents/address.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/utils/bigint.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/217
=> checksummed address function

extension/app/ts/background/background.ts, extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/utils/wire-types.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/226
=> `getLogs`, topics for logs, `getTransactionCount` bug

extension/app/ts/components/pages/ChangeChain.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/components/pages/InterceptorAccessList.tsx, extension/app/ts/components/pages/PersonalSign.tsx
=> swap positive and negative buttons with each other in the UI's

extension/app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx
=> detect if we do don't see any important visible changes, and show a message in such case

extension/app/css/interceptor.css, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx
fixes https://github.com/DarkFlorist/TheInterceptor/issues/248
=> Fix importance box overflow

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/settings.ts, extension/app/ts/utils/semaphore.ts, extension/app/ts/utils/typescript.ts, extension/app/ts/utils/visualizer-types.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/251
This also gets rid of more global variables
=> store simulation results to protect against worker shutdown

extension/app/ts/background/backgroundUtils.ts, extension/app/ts/components/App.tsx
- Use absolute path for V2 urls
=> Fix creating tabs like Address Book on *nix systems

extension/app/ts/background/background.ts, extension/app/ts/background/providerMessageHandlers.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/275
=> get rid of `globalThis.interceptor.signerChain`

extension/app/ts/components/formVisualizerResults.ts, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, extension/app/ts/components/simulationExplaining/customExplainers/MakeMeRich.tsx, extension/app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, extension/app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx, extension/app/ts/utils/user-interface-types.ts, extension/app/ts/utils/visualizer-types.ts
- refactor: envelope simulatedAndVisualized trasactions transaction object as separate tx
- Fixes https://github.com/DarkFlorist/TheInterceptor/issues/102
=> simTransaction enveloping & deleting richTx

extension/app/ts/background/background.ts, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/simulation/simulator.ts, extension/app/ts/utils/constants.ts, extension/test/tests/nethermindComparison.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/194
=> bundle transaction and website

extension/app/ts/background/iconHandler.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/185
=> no need intermediateFunction

extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/utils/calldata.ts, extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/user-interface-types.ts, extension/app/ts/utils/visualizer-types.ts, extension/app/ts/utils/wire-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/213
=> replace `funtypes.Object` with `funtypes.ReadonlyObject`

extension/app/ts/background/settings.ts, extension/app/ts/utils/typescript.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/294
=> Storage keys typing

extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/utils/wire-types.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/293
=> getLogs can take array as an address too

extension/app/ts/background/windows/personalSign.ts, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/wire-types.ts, extension/test/tests/signTypedData.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/290
=> Fix EIP712 parsing

extension/app/ts/background/settings.ts, extension/app/ts/simulation/services/EthereumClientService.ts, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/utils/visualizer-types.ts
Backend work for https://github.com/DarkFlorist/TheInterceptor/issues/209
=> get token balances after transaction in simulation

extension/app/ts/background/background.ts, extension/app/ts/background/metadataUtils.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/background/windows/confirmTransaction.ts, extension/app/ts/simulation/protectors/commonTokenOops.ts, extension/app/ts/simulation/protectors/eoaApproval.ts, extension/app/ts/simulation/protectors/eoaCalldata.ts, extension/app/ts/simulation/protectors/feeOops.ts, extension/app/ts/simulation/protectors/selfTokenOops.ts, extension/app/ts/simulation/protectors/tokenToContract.ts, extension/app/ts/simulation/protectors/unverifiedApproval.ts, extension/app/ts/simulation/services/EthereumClientService.ts, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/simulation/simulator.ts, extension/app/ts/utils/visualizer-types.ts, extension/test/tests/SimulationModeEthereumClientService.ts, extension/test/tests/nethermindComparison.ts
- Make Simulationmodeclient to be a set of functions instead of a class (fixes https://github.com/DarkFlorist/TheInterceptor/issues/222 )
- Fix couple race condition issues
- refactor prepend mode. fixes https://github.com/DarkFlorist/TheInterceptor/issues/221
=> Refactor simulationmode client service (sorry for big PR 😬 )

extension/app/ts/backgroundServiceWorker.ts, extension/package-lock.json, extension/package.json
fixes https://github.com/DarkFlorist/TheInterceptor/issues/295
=> fixed Register Content Scripts

extension/app/ts/simulation/priceEstimator.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/229
=> use `decodeFunctionResult` instead of `parseCallResult`

extension/app/ts/background/background.ts, extension/app/ts/background/iconHandler.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/providerMessageHandlers.ts, extension/app/ts/background/settings.ts, extension/app/ts/background/windows/changeChain.ts, extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/components/App.tsx, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/typescript.ts, extension/app/ts/utils/visualizer-types.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/306 . This PR changes us to first change address eg, quickly and then update simulation state when it finishes running
=> Unify address/chain/simulation mode changing to one place

extension/app/ts/background/background.ts, extension/app/ts/background/backgroundUtils.ts, extension/app/ts/background/windows/confirmTransaction.ts, extension/app/ts/components/formVisualizerResults.ts, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/simulationExplaining/Transactions.tsx, extension/app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, extension/app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, extension/app/ts/components/simulationExplaining/identifyTransaction.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/simulation/logHandlers.ts, extension/app/ts/simulation/services/LogSummarizer.ts, extension/app/ts/simulation/simulator.ts, extension/app/ts/utils/visualizer-types.ts
this should fix https://github.com/DarkFlorist/TheInterceptor/issues/317 as well. But I wasn't able to generate such transaction with uniswap now to test it.
=> refactor, instead of using `is721` flag, use `type` flag instead. Add `BeforeAfterBalance` to swap identification

extension/app/css/interceptor.css, extension/app/ts/components/simulationExplaining/SwapTransactions.tsx, extension/app/ts/components/subcomponents/coins.tsx, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts
fixes: https://github.com/DarkFlorist/TheInterceptor/issues/209
=> Show balance change on swaps

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/windows/personalSign.ts, extension/app/ts/components/formVisualizerResults.ts, extension/app/ts/components/pages/ConfirmTransaction.tsx, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/utils/interceptor-messages.ts
partial fix for https://github.com/DarkFlorist/TheInterceptor/issues/105
Doesn't work with approve access dialog yet
=> Refresh metadata when address book changes for confirm transaction and personal sign views

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/components/pages/ChangeChain.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/utils/interceptor-messages.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/105
=> fix metadata refreshing in access request dialog too

extension/app/ts/components/pages/AddNewAddress.tsx, extension/app/ts/components/pages/InterceptorAccess.tsx, extension/app/ts/utils/user-interface-types.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/338
=> Fix modify and switch

extension/app/ts/components/pages/ChangeChain.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/150
=> guard clause and styling, also remove [] from useEffect

extension/app/ts/background/iconHandler.ts, extension/app/ts/components/pages/Home.tsx, extension/app/ts/utils/constants.ts, extension/app/ts/utils/interceptor-messages.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/326
Show this instead if not on a dapp page:
=> Improve signer explanation

extension/app/inpage/ts/inpage.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/172
=> Add bind to injects and some styling changes

extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/simulation/protectors/eoaApproval.ts, extension/app/ts/simulation/protectors/eoaCalldata.ts, extension/app/ts/simulation/protectors/quarantine-codes.ts, extension/app/ts/simulation/protectors/tokenToContract.ts, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/utils/constants.ts
- show warning if gas limit is reached
- throw error for getCode call if the call fails
fix https://github.com/DarkFlorist/TheInterceptor/issues/321
=> Handle gas full for `getcode`

extension/app/ts/background/background.ts, extension/app/ts/components/pages/Home.tsx, extension/app/ts/components/subcomponents/Error.tsx, extension/app/ts/components/subcomponents/SomeTimeAgo.tsx, extension/app/ts/simulation/services/EthereumClientService.ts, extension/app/ts/simulation/simulator.ts, extension/app/ts/utils/interceptor-messages.ts, extension/test/tests/nethermindComparison.ts
fixes partially: https://github.com/DarkFlorist/TheInterceptor/issues/335
we still need to manage this error in other places to fix the issue completely
=> unable to connect to network error dialog

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/windows/confirmTransaction.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/309
=> unify `updateSimulationState` and `refreshConfirmTransactionSimulation`

extension/app/ts/background/background.ts, extension/app/ts/background/popupMessageHandlers.ts, extension/app/ts/background/settings.ts, extension/app/ts/background/simulationModeHanders.ts, extension/app/ts/simulation/priceEstimator.ts, extension/app/ts/simulation/services/EthereumClientService.ts, extension/app/ts/simulation/services/EthereumSubscriptionService.ts, extension/app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/app/ts/simulation/simulator.ts, extension/app/ts/utils/constants.ts, extension/app/ts/utils/typescript.ts, extension/app/ts/utils/visualizer-types.ts, extension/test/tests/nethermindComparison.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/302
we also reorg the simulated block on top when new block arrives
=> Fix ethereum subscriptions

extension/app/css/interceptor.css, extension/app/ts/components/pages/PersonalSign.tsx, extension/app/ts/components/simulationExplaining/SimulationSummary.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/361
fix https://github.com/DarkFlorist/TheInterceptor/issues/354
=> get rid of textarea

extension/app/ts/utils/interceptor-messages.ts, extension/app/ts/utils/visualizer-types.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/283
=> OptionalEthereumAddress

extension/app/ts/background/windows/interceptorAccess.ts, extension/app/ts/components/pages/InterceptorAccess.tsx
- now if app first asks to access to interceptor and then to address, we update the access request dialog and disable the buttons for 3 secs
Fix https://github.com/DarkFlorist/TheInterceptor/issues/147
=> Update pending access right request if new one comes

app/ts/background/background.ts, app/ts/background/windows/personalSign.ts, app/ts/components/pages/PersonalSign.tsx, app/ts/utils/personal-message-definitions.ts
=> identify `SafeTx` message type and make a very simple and dumb viz

app/ts/components/pages/PersonalSign.tsx
=> Show raw message along with decoded one

app/ts/background/background.ts, app/ts/background/windows/personalSign.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/406
=> remove try parsing

app/html/addressBook.html, app/html/background.html, app/html/changeChain.html, app/html/confirmTransaction.html, app/html/interceptorAccess.html, app/html/personalSign.html, app/html/popup.html, app/manifestV2.json, app/ts/components/App.tsx, app/ts/components/subcomponents/SomeTimeAgo.tsx, build/bundler.mts, build/vendor.mts, package-lock.json, package.json
fixes https://github.com/DarkFlorist/TheInterceptor/issues/399
fixes https://github.com/DarkFlorist/TheInterceptor/issues/373
=> Add signals and update SomeTimeAgo properly

app/ts/components/pages/Home.tsx, app/ts/components/subcomponents/signers.tsx
fixes https://github.com/DarkFlorist/TheInterceptor/issues/400
Makes UI more clear about informing that there's no wallet connection
=> No signer connection UI update

app/css/interceptor.css, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/subcomponents/Spinner.tsx
text used to overflow over the screen here.
=> fix text overflow on spinner

app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/409
=> fix simulation mode and signing mode mixup

app/ts/AddressBook.tsx, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/background/windows/personalSign.ts, app/ts/components/App.tsx, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ChangeActiveAddress.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/NotificationCenter.tsx, app/ts/simulation/priceEstimator.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, test/tests/SimulationModeEthereumClientService.ts, test/tests/nethermindComparison.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/402
=> remove some unnecessary as consts

app/ts/utils/eip712Parsing.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/420
=> allow number inputs for integer too

app/ts/simulation/services/SimulationModeEthereumClientService.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/428
=> fix getSimulatedCode parsing

app/ts/background/background.ts
Allow only 20 pending requests per connection at once to prevent extension from crashing for spammy dapps
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/423
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/424
=> Rate limiter for pending requests

app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/simulationModeHanders.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/subcomponents/SomeTimeAgo.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/simulation/simulator.ts, app/ts/utils/interceptor-messages.ts, app/ts/utils/visualizer-types.ts, test/tests/nethermindComparison.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/435
=> Transaction created timestamp

app/ts/components/subcomponents/PreactBlocky.tsx, app/ts/components/subcomponents/address.tsx, app/ts/components/subcomponents/coins.tsx, app/ts/utils/preact-utilities.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/433
=> tighten blockie

app/img/settings.svg, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/App.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/utils/interceptor-messages.ts, app/ts/utils/user-interface-types.ts
=> settings menu with tab/popup option

app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/utils/visualizer-types.ts
Fixes typing of transfer identification
=> Fix simple transfer

app/ts/background/simulationModeHanders.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/434
There's currently bug that this will refresh nonces of raw transactions. I'll fix that next
=> No Simulation gas for eth_call and refresh nonces on nonce failures

app/ts/background/simulationModeHanders.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/utils/visualizer-types.ts, app/ts/utils/wire-types.ts
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/466
=> input / data mismatch

app/ts/components/subcomponents/address.tsx
the website field was cutting off wrong, now it ellipses:
=> ellipse website element

app/css/interceptor.css, app/ts/AddressBook.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/120
=> fit content for addressbook

app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/OpenSeaOrder.tsx, app/ts/components/subcomponents/address.tsx, app/ts/components/ui-utils.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/438
=> add some missing fields to raw transaction details

app/ts/background/settings.ts, app/ts/backgroundServiceWorker.ts, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/utils/sleep.ts, app/ts/utils/storageUtils.ts, app/ts/utils/typescript.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/214
=> clean typescript.ts and add guard clauses to identify transaction

app/ts/AddressBook.tsx, app/ts/components/formVisualizerResults.ts, app/ts/components/pages/ChangeActiveAddress.tsx, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/SwapTransactions.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, extension/.vscode/settings.json
fix https://github.com/DarkFlorist/TheInterceptor/issues/284
=> align multiline trinary code style

app/ts/background/simulationModeHanders.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/483
=> do not use simulation state in signing mode

app/ts/background/background.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/485
=> fix and update nonces in confirm transaction view

app/css/interceptor.css, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/settings.ts, app/ts/background/storageVariables.ts, app/ts/components/pages/SettingsView.tsx, app/ts/utils/interceptor-messages.ts, app/ts/utils/wire-types.ts
fix: https://github.com/DarkFlorist/TheInterceptor/issues/207
=> Import export settings

app/ts/background/windows/changeChain.ts, app/ts/components/pages/ChangeChain.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/538
=> fix font in change chain

app/ts/utils/wire-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/pull/533
=> add constraint to DappRequestTransaction

app/ts/background/background.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/550
=> don't double verify access (fixes the firefox issue that can happen on chrome too)

app/inpage/ts/inpage.ts, app/ts/background/background.ts, app/ts/simulation/services/EthereumJSONRpcRequestHandler.ts, app/ts/utils/errors.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/549
fix https://github.com/DarkFlorist/TheInterceptor/issues/545
=> Better error handling

app/ts/components/pages/AddNewAddress.tsx, app/ts/utils/bigint.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/557
=> Trim address on active address adding and don't crash on non-valid address

app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/simulationModeHanders.ts, app/ts/background/windows/changeChain.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/background/windows/interceptorAccess.ts, app/ts/background/windows/personalSign.ts, app/ts/components/App.tsx, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/subcomponents/ChainSelector.tsx, app/ts/components/ui-utils.tsx, app/ts/utils/interceptor-messages.ts, app/ts/utils/user-interface-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/492
when tab is refreshed it loses it's state. This PR makes it so that on refresh the tab will request the data from storage again. This system is added to all popup views that we have (addressbook works with refresh)
=> Fix view refreshing when using tabs

app/ts/background/background.ts, app/ts/background/iconHandler.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/components/App.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/customExplainers/OpenSeaOrder.tsx, app/ts/components/ui-utils.tsx, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/simulator.ts, app/ts/utils/interceptor-messages.ts, app/ts/utils/storageUtils.ts, app/ts/utils/user-interface-types.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/397
=> Block time warning

app/ts/background/accessManagement.ts, app/ts/background/background.ts, app/ts/background/messageSending.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/providerMessageHandlers.ts, app/ts/background/simulationModeHanders.ts, app/ts/background/storageVariables.ts, app/ts/background/windows/changeChain.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/background/windows/interceptorAccess.ts, app/ts/background/windows/personalSign.ts, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/simulation/services/EthereumSubscriptionService.ts, app/ts/utils/interceptor-messages.ts, app/ts/utils/personal-message-definitions.ts, app/ts/utils/requests.ts
One possible fix for the first issue of https://github.com/DarkFlorist/TheInterceptor/issues/567 . However, I think its unlikely it was caused by this, so I continue looking for that.
=> Instead of using requestID as unique identifier across connections (its not), add uniqueRequestIdentifier that is unique

app/ts/components/pages/Home.tsx
I removed that we check that this has actually happened to show the time error for debugging reasons and forgot to add the check back
=> noNewBlockForOverTwoMins

app/ts/AddressBook.tsx, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ChangeActiveAddress.tsx, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/InterceptorAccessList.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/495
=> remove <p> nesting

app/ts/simulation/priceEstimator.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/utils/constants.ts, app/ts/utils/multicall-types.ts
Calculate eth balance changes via eth logs and with a balance query
=> eth balance handling for Execution spec 383

app/img/signers/coinbasewallet.svg, app/inpage/ts/inpage.ts, app/ts/components/subcomponents/signers.tsx, app/ts/utils/constants.ts, app/ts/utils/user-interface-types.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/586
=> add support for coinbase wallet and send `ethereum#initialized` when injected

app/ts/background/windows/changeChain.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/592
=> close chain dialog when approved/disapproved

app/ts/background/simulationModeHanders.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/utils/interceptor-messages.ts
fix: https://github.com/DarkFlorist/TheInterceptor/issues/565
=> when rejecting transaction, forward the error to dapp if the transaction fails

app/inpage/ts/inpage.ts, app/ts/background/background-startup.ts, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/providerMessageHandlers.ts, app/ts/background/settings.ts, app/ts/background/simulationModeHanders.ts, app/ts/components/App.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/utils/interceptor-messages.ts, app/ts/utils/storageUtils.ts, app/ts/utils/user-interface-types.ts
fix: https://github.com/DarkFlorist/TheInterceptor/issues/508
With `window.ethereum.send` I did not figure out how it should work as the page I was testing with went offline (peepeth.com)
=> Adds Metamask compatibility mode

app/ts/components/simulationExplaining/SwapTransactions.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/utils/abi.ts, app/ts/utils/typescript.ts, app/ts/utils/visualizer-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/603
=> add erc1155 swap visualization support

app/ts/background/background-startup.ts, app/ts/background/popupMessageHandlers.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/simulator.ts, app/ts/utils/errors.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/501
if `fetch` fails to various different networking errors, popup stopped working. Now we display always allow the popup to be seen but show the warning to user
=> fix another bug of not displaying popup dialog on error

app/ts/AddressBook.tsx, app/ts/background/background.ts, app/ts/background/medataSearch.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/AddNewAddress.tsx, app/ts/utils/addressBookTypes.ts, app/ts/utils/interceptor-messages.ts
- Allow adding of any address types in address book
- When adding new address, check if we already have address, if so, do not allow
- Prefill the fields from chain for the ones we have available (decimals)
=> Adding any address types

app/ts/background/background.ts, app/ts/background/medataSearch.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/AddNewAddress.tsx, app/ts/utils/interceptor-messages.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/626
Do not allow user to add addresses with duplicate name or symbol in them
=> Duplicate name or symbol

app/ts/AddressBook.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/636
=> add information source to addressbook and allows user to edit any other than dark florist metadata and interceptor addresses

app/css/interceptor.css, app/ts/background/metadataUtils.ts, app/ts/components/subcomponents/coins.tsx, app/ts/utils/tokenIdentification.ts, app/ts/utils/visualizer-types.ts
show untrusted information about tokens when we don't have data available. The point is to raise awareness for users to look more what the token is. The point is then in https://github.com/DarkFlorist/TheInterceptor/issues/98 to show that what the blinkin is. Also with https://github.com/DarkFlorist/TheInterceptor/issues/581 the idea is to make it possible for user to add the token
The warning sign is also blinking
=> show untrusted token name and ticker for token

app/css/interceptor.css, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/SwapTransactions.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/OpenSeaOrder.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, app/ts/components/subcomponents/coins.tsx, app/ts/components/ui-utils.tsx, app/ts/simulation/services/LogSummarizer.ts, app/ts/utils/constants.ts, app/ts/utils/tokenIdentification.ts, app/ts/utils/visualizer-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/581
Allows user to rename tokens when they appear
=> Token renaming from transactions

app/ts/components/pages/AddNewAddress.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/638
=> Onchain information error

app/css/interceptor.css, app/ts/background/background.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/components/App.tsx, app/ts/components/formVisualizerResults.ts, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/SwapTransactions.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, app/ts/components/subcomponents/coins.tsx, app/ts/simulation/services/LogSummarizer.ts, app/ts/utils/ethereumNameService.ts, app/ts/utils/interceptor-messages.ts, app/ts/utils/typed-arrays.ts, app/ts/utils/user-interface-types.ts, app/ts/utils/visualizer-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/624
shows ENS name transfer when transferring ENS wrapped erc1155's. We are missing this address from address metadata, I added issue about this: https://github.com/DarkFlorist/address-metadata/issues/12 . We should refactor that repo and figure out how to get it more comprehensive.
=> add ENS name resolution

app/ts/components/pages/ConfirmTransaction.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/641
=> Fixes confirm transaction showing old data

app/ts/background/settings.ts, app/ts/components/subcomponents/ChainSelector.tsx, app/ts/simulation/services/EthereumClientService.ts, app/ts/types/multicall-types.ts
=> support for multicall in geth

app/ts/components/pages/PersonalSign.tsx, app/ts/utils/bigint.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/613
=> do not encode signed message if its not a number

app/ts/background/background.ts, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/simulation/compoundGovernanceFaking.ts, app/ts/types/interceptor-messages.ts, app/ts/utils/abi.ts, app/ts/utils/calldata.ts, app/ts/utils/constants.ts
- show what you are voting for
- support for more different voting functions
- fix https://github.com/DarkFlorist/TheInterceptor/issues/718
=> show the vote itself

app/ts/AddressBook.tsx
=> Show abi in addressbook

app/ts/AddressBook.tsx, app/ts/background/medataSearch.ts, app/ts/components/pages/AddNewAddress.tsx
- Now user is able to add ABI to metadata entries
fix https://github.com/DarkFlorist/TheInterceptor/issues/729
=> Add abi to metadata addr

app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx, app/ts/components/subcomponents/solidityType.tsx, app/ts/components/ui-utils.tsx, app/ts/types/user-interface-types.ts, app/ts/types/visualizer-types.ts
fixes the issue discussed in meeting about the usestate's and also enriches events with metadata
- Fix https://github.com/DarkFlorist/TheInterceptor/issues/726
=> Log metadata and usestate fix

app/ts/background/settings.ts
Fixes export settings. Does not fix the import settings problem on firefox
=> Fix export settings

app/css/interceptor.css, app/html/settingsView.html, app/html3/settingsViewV3.html, app/manifestV2.json, app/ts/background/background.ts, app/ts/background/backgroundUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/components/App.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/components/subcomponents/DinoSays.tsx, app/ts/settingsView.ts, app/ts/types/interceptor-messages.ts, app/ts/utils/storageUtils.ts
Moves settings view to a tab. This fixes the FireFoxes setting import thing as well.
=> Move settings to a tab

app/ts/components/pages/AddNewAddress.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/751
=> areInputsValid

app/ts/components/pages/PersonalSign.tsx
Seems like using `key` as variable name is not good idea and produces `undefined`, I am not really sure why, but this fixes the issue
=> Fix visualization for unidentified EIP712 message

app/css/interceptor.css, app/ts/background/background.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/types/accessRequest.ts, app/ts/types/interceptor-messages.ts, app/ts/types/visualizer-types.ts, app/ts/utils/solidityTypes.ts, test/tests/nethermindComparison.ts
- fixes bug that if you had two governance simulations on your transaction stack, only one of was working
- fixes bug that metadata of governance contract did not refresh even thought refresh was clicked
=> Update governance simulation state properly

app/css/interceptor.css, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, app/ts/components/subcomponents/coins.tsx
=> Cleans up styling

app/inpage/ts/inpage.ts, app/ts/background/background-startup.ts, app/ts/background/background.ts, app/ts/background/providerMessageHandlers.ts, app/ts/background/windows/interceptorAccess.ts, app/ts/types/JsonRpc-types.ts
- fix https://github.com/DarkFlorist/TheInterceptor/issues/771
- fixes connecting to ENS
fixes bugs in access management:
- on race condition that multiple requests are made that requires access, they are all queued and replied at once
- handle long chains of access requests:
1) dapp asks access for account on signing mode
-> we prompt access to site
-> provider prompt to get address from provider 
-> interceptor prompt access to address that were gotten from provider
-> reply to dapp that we have access
=> Access management

app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/ui-utils.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/777
=> don't block with etherscan error, remove debug printing

app/ts/simulation/simulator.ts
Handle logs from 0x0 address as erc20 logs, as they are the new ETH logs from multicall
=> forgot that 0x0 is special case for erc20 event handling

app/css/interceptor.css
My mistake in previous PR, I put font size in `.small-address-container::after` instead of `.small-address-container`.
=> Fixes a bug in badge rendering.

app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/subcomponents/link.tsx, app/ts/types/interceptor-messages.ts, app/ts/utils/websiteData.ts
Fix https://github.com/DarkFlorist/TheInterceptor/issues/806
=> website recommendations

app/inpage/ts/inpage.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/745
fix https://github.com/DarkFlorist/TheInterceptor/issues/708
https://eip6963.org/
=> fix coinbase wallet connection and EIP6963

app/ts/components/simulationExplaining/SimulationSummary.tsx
=> Fix capitalization in tokenEventsSingular

app/ts/components/pages/ChangeActiveAddress.tsx, app/ts/components/subcomponents/address.tsx
fixes https://github.com/DarkFlorist/TheInterceptor/issues/801
=> Don't show edit address on change active address

app/ts/background/background-startup.ts, app/ts/background/background.ts, app/ts/background/iconHandler.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/App.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/Home.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/subcomponents/Error.tsx, app/ts/types/interceptor-messages.ts, app/ts/utils/errors.ts, app/ts/utils/requests.ts
Try catching all errors that haven't been caught before and show them to user if there's a dialog open. Otherwise print them to console
fixes https://github.com/DarkFlorist/TheInterceptor/issues/829
=> Handle unexpected errors

app/ts/background/background.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/840
=> fix timeout error reporting

app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/simulation/simulator.ts
When metadata changes, update logs with the new metadata as well
fix https://github.com/DarkFlorist/TheInterceptor/issues/811
=> Refresh logs on metadata update like other metadata

app/ts/simulation/services/SimulationModeEthereumClientService.ts
There's a bug that if you have old transaction stack, the transactions in the stack might have base fees that no longer work (or are too high to be reasonable), then the simulation will fail. This PR changes it so that every time we refresh, we set the basefee fees for 2x parent block
=> automatically adjust baseFeePerGas for transactions before refreshing a simulation

app/ts/background/background-startup.ts, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/components/pages/Home.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/simulation/simulator.ts
- also change goerlis rich address to a new one that is rich
=> Fix issue that results chain ID to be different on network selector and simulator

app/ts/utils/websiteData.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/862
=> set https://2.horswap.eth.limo/ as alternative for uniswap

app/inpage/ts/inpage.ts, app/ts/background/background.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/881
=> fix address and chain id changing

app/ts/components/pages/ConfirmTransaction.tsx
Previous pr's refactor removed the current pending transaction from this names list. This adds it back
=> show current pending transaction / message in names list

app/ts/background/backgroundUtils.ts, app/ts/background/iconHandler.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/windows/changeChain.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/background/windows/interceptorAccess.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/ui-utils.tsx, app/ts/utils/constants.ts, app/ts/utils/requests.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/892
=> fix no tab id

app/ts/background/windows/personalSign.ts, app/ts/simulation/protectors/chainIdMismatch.ts, app/ts/simulation/simulator.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/463
=> check chain id for transactions and improve the error for messages

app/ts/simulation/services/LogSummarizer.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/894
fix https://github.com/DarkFlorist/TheInterceptor/issues/48
=> show gas fees in summary

app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/types/JsonRpc-types.ts, test/RPCResponses.ts, test/tests/nethermindComparison.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/584
returns now (with 0 spending transaction):
=> fix getSimulatedStack

app/ts/background/background.ts, app/ts/background/simulationModeHanders.ts, app/ts/background/storageVariables.ts, app/ts/simulation/compoundGovernanceFaking.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/types/JsonRpc-types.ts, app/ts/types/interceptor-messages.ts, app/ts/types/multicall-types.ts, app/ts/types/visualizer-types.ts, test/tests/nethermindComparison.ts
- keep 1.0.0 version that returns gas prices calculated wrong
- add 1.01 version that has this fixed
=> separate 1.0.0 and 1.01 versions simulationStack calls

app/ts/components/formVisualizerResults.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/607
=> don't ignore events that are from mismatching token contract

app/inpage/ts/document_start.ts, app/inpage/ts/inpage.ts, app/ts/AddressBook.tsx, app/ts/background/iconHandler.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/MakeMeRich.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/components/subcomponents/Error.tsx, app/ts/components/subcomponents/address.tsx, app/ts/components/ui-utils.tsx, app/ts/simulation/services/EtherScanAbiFetcher.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/simulation/simulator.ts, app/ts/types/wire-types.ts, app/ts/utils/constants.ts, app/ts/utils/solidityTypes.ts, app/ts/utils/websiteData.ts, test/MockRequestHandler.ts, test/tests/nethermindComparison.ts
Replace string literals with string whenever no replacements are done with them
=> Change template literals containing no replacements

app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx
fixes a bug that gas fees were already deducted from `before` even thought they should still be there. Now with rich mode your before amount is 200k, and not 199...
=> add gas fees back to "before" fields

app/ts/utils/bigint.ts
https://docs.alchemy.com/reference/eth-feehistory
=> eth-feehistory should return all 0's on empty block

app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/ProxySendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/utils/depthFirstSearch.ts, app/ts/utils/typed-arrays.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/977
fix https://github.com/DarkFlorist/TheInterceptor/issues/944
=> Proxy transfer

app/ts/components/pages/ConfirmTransaction.tsx
=> add making you rich back to confirm tx

package-lock.json, package.json, test/tests/metadataUtils.ts
fixes ENS name resolution on token sends:
=> pump address metadata

app/ts/background/background.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/simulation/logHandlers.ts, app/ts/simulation/simulator.ts, app/ts/types/ens.ts, app/ts/types/visualizer-types.ts, app/ts/utils/constants.ts, app/ts/utils/storageUtils.ts
show label names in logs as well (the id=..., is originally just labelhash):
=> resolve ens label hashes

app/ts/background/metadataUtils.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/simulation/logHandlers.ts, app/ts/simulation/simulator.ts, app/ts/types/visualizer-types.ts, app/ts/utils/constants.ts
=> ens transfer

app/ts/simulation/simulator.ts
=> merge public resolver 1 and 2 handling

app/ts/background/metadataUtils.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/simulation/logHandlers.ts, app/ts/simulation/simulator.ts, app/ts/types/visualizer-types.ts, app/ts/utils/constants.ts
=> new owner and resolver

app/ts/background/windows/confirmTransaction.ts, app/ts/components/simulationExplaining/customExplainers/ProxySendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx
I removed token results field couple of prs ago but it was not removed from these places. This fixes the issue
=> fix token handling as token results was removed

app/ts/components/formVisualizerResults.ts, app/ts/simulation/logHandlers.ts, app/ts/simulation/simulator.ts, app/ts/types/visualizer-types.ts, app/ts/utils/constants.ts
=> ens name unwrapped

app/ts/background/metadataUtils.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1011
=> don't cache reverse label guesses unless they are correct

app/ts/components/subcomponents/EnsGradient.tsx, app/ts/components/subcomponents/LICENSE_ens.md, app/ts/components/subcomponents/LICENSE_zorb.md, app/ts/components/subcomponents/ens.tsx, app/ts/utils/bigint.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1015
=> add ens gradient icon

app/css/interceptor.css, app/ts/background/background.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/storageVariables.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/components/formVisualizerResults.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx, app/ts/components/subcomponents/ens.tsx, app/ts/simulation/logHandlers.ts, app/ts/simulation/simulator.ts, app/ts/types/interceptor-messages.ts, app/ts/types/visualizer-types.ts, app/ts/utils/storageUtils.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1012
=> Ens english

app/ts/utils/ethereumNameService.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/991
=> verify name gotten from rpc

app/ts/types/visualizer-types.ts, app/ts/utils/ethereumNameService.ts
now fuses texts are a bit more readable
=> make fuses flags more readable

package-lock.json, package.json
fix https://github.com/DarkFlorist/TheInterceptor/issues/995
=> bump address metadata

app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx
=> show datestrings instead of numbers

app/ts/AddressBook.tsx, app/ts/background/accessManagement.ts, app/ts/background/background-startup.ts, app/ts/background/backgroundUtils.ts, app/ts/background/iconHandler.ts, app/ts/background/storageVariables.ts, app/ts/components/App.tsx, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/types/addressBookTypes.ts, app/ts/types/user-interface-types.ts, app/ts/utils/storageUtils.ts
now you can setup the blocks to be address level too
=> Address level blocking

app/css/interceptor.css, app/img/warning-sign-white.svg, app/ts/components/pages/Home.tsx, app/ts/components/subcomponents/ChainSelector.tsx
| <img width="516" alt="Screenshot 2024-06-20 at 3 02 39 PM" src="https://github.com/DarkFlorist/TheInterceptor/assets/1169838/32ef38d7-f2e2-47ed-9282-4f7f3becb7c4"> | <img width="516" alt="Screenshot 2024-06-20 at 3 00 40 PM" src="https://github.com/DarkFlorist/TheInterceptor/assets/1169838/fc83b1a4-4e15-46d3-97ab-6cf0fb4da7f6"> |
|:--:|:--:|
| _default dropdown_ | _extended label_ |
| <img width="516" alt="Screenshot 2024-06-20 at 3 01 17 PM" src="https://github.com/DarkFlorist/TheInterceptor/assets/1169838/7a63f19f-8340-43ac-a801-2f56ba5cc3f0"> | ![dropdown-button](https://github.com/DarkFlorist/TheInterceptor/assets/1169838/bb8faba2-f798-45f7-a882-775639887cb7) |
|:--:|:--:|
| _label with warning_ | _animation_ |
=> Wallet info and chain selector UI enhancement

app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx
just stumbled upon a typo when searching through code (word didn't find match)
=> Fix typo on word "Arbitrary"

app/css/interceptor.css, app/html/addressBook.html, app/html3/addressBookV3.html, app/ts/AddressBook.tsx, app/ts/components/subcomponents/DynamicScroller.tsx, app/ts/types/interceptor-messages.ts
=> Fix addressbook erratic navigation behavior

app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/customExplainers/GnosisSafeVisualizer.tsx, app/ts/types/interceptor-messages.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1041
=> fix pending metadata updating for signed messages

app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/subcomponents/coins.tsx, app/ts/simulation/services/LogSummarizer.ts, app/ts/types/visualizer-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/590
=> use token component and not ether

app/ts/background/background.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
Realized effective gas price should be calculated from the current block and not from future block. Also renamed method to better suit its purpose
=> effective gas price fix

app/inpage/ts/inpage.ts, app/ts/background/background.ts, app/ts/background/providerMessageHandlers.ts, app/ts/types/interceptor-messages.ts
- When interceptor is on a unsupported network, forward all the messages to the provider instead
=> unsupported networks

app/ts/background/background.ts, app/ts/background/settings.ts, app/ts/background/storageVariables.ts, app/ts/types/rpc.ts, app/ts/utils/storageUtils.ts
- when rpc is selected, promote it as primary
- when searching for a primary rpc, first search among primary's and then among non-primary's
=> primary rpc fix

app/css/interceptor.css, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx, app/ts/components/subcomponents/coins.tsx, app/ts/utils/constants.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1084
=> remove font size constant

app/ts/types/ethSimulate-types.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1088
=> ethSimulateV1ParamObject -> EthSimulateV1ParamObject

app/ts/background/metadataUtils.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1007
=> retrieveEnsNodeHashes refactor

app/ts/simulation/protectors/sendToNonContactAddress.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/796
=> change wording to be about the transaction and not about the user

app/css/interceptor.css, app/ts/background/windows/personalSign.ts, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/subcomponents/ParsedInputData.tsx, app/ts/components/subcomponents/ViewSelector.tsx, app/ts/types/personal-message-definitions.ts
=> Use input component where appropriate

app/ts/components/pages/PersonalSign.tsx, app/ts/components/subcomponents/ParsedInputData.tsx, app/ts/components/subcomponents/ViewSelector.tsx
Tries to guess which is right to show, raw input data or parsed input data
fixes https://github.com/DarkFlorist/TheInterceptor/issues/1052
=> Default inputdata option

app/ts/background/windows/interceptorAccess.ts, app/ts/components/App.tsx, app/ts/components/pages/ChangeActiveAddress.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/types/user-interface-types.ts
fixes https://github.com/DarkFlorist/TheInterceptor/issues/783
=> display all pending requests at once

app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx
=> fix ens fuses setting to be visible

app/ts/components/subcomponents/ChainSelector.tsx
just noticed the chain selector lost width with the truncate class update
=> Fix truncated chain selector

app/ts/background/websiteAccessSearch.ts, app/ts/components/pages/WebsiteAccess.tsx
Result was empty even if there were matches
=> Fix false matches in search result

app/ts/background/metadataUtils.ts, app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/1108
=> fix fuses for name wrapped event

app/ts/components/pages/ConfirmTransaction.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/1111
=> fix error icon

app/ts/simulation/services/SimulationModeEthereumClientService.ts
There's an bug that if an website tries to estimate gas for a transaction that fails, the simulate estimate throws undefined error. Instead of that, we should just forward the error to website (can be tested by trying to send eth on lunaria when you don't have enough)
=> don't throw simulate estimate gas failure but instead send it to the website

app/ts/background/popupMessageHandlers.ts, app/ts/components/pages/ConfirmTransaction.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/1099
=> fix transaction simulation state update

.gitattributes
[Reference](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)
=> General git configuration for line endings

app/css/interceptor.css, app/ts/background/background.ts, app/ts/background/popupMessageHandlers.ts, app/ts/background/windows/confirmTransaction.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/SimulationSummary.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/subcomponents/AutosizingInput.tsx, app/ts/components/ui-utils.tsx, app/ts/types/interceptor-messages.ts, app/ts/types/user-interface-types.ts, app/ts/utils/OptionalSignal.ts, package-lock.json, package.json
=> add gas limit change button

app/ts/background/medataSearch.ts
=> Fix addressbook search to be case-insensitive

app/ts/components/subcomponents/address.tsx
Fixes issues with #1156 with the ui not showing named address and missing icon
=> Fix address ui not showing named address in addressbook

app/css/interceptor.css, app/ts/components/simulationExplaining/Transactions.tsx
=> fix nontokenlog view

app/ts/background/background.ts, app/ts/background/metadataUtils.ts, app/ts/background/popupMessageHandlers.ts, app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx
- fix https://github.com/DarkFlorist/TheInterceptor/issues/1145
- fix issue that we were trying to add `something.eth.eth` nodes that do not match anywhere
- fix issue where we just added new ens nodes but then did not utilize them right away so user had to wait for next block to resolve new domains
=> fix wrap event

readme.md
fix https://github.com/DarkFlorist/TheInterceptor/issues/1171
=> change readme.md in a way that its not mandatory to use our nodes

app/css/interceptor.css, app/ts/components/subcomponents/InlineCard.tsx, app/ts/components/subcomponents/coins.tsx
[UI Demo Page](https://darkflorist-ui.pages.dev/#demo:smalladdress)
=> Add option to not expand buttons on address

app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/types/visualizer-types.ts, app/ts/types/wire-types.ts, app/ts/utils/ethereum.ts
add https://optimism.blockpi.network/v1/rpc/public as rpc to test
=> add support for optimism

app/ts/utils/constants.ts, app/ts/utils/tokenIdentification.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1174
=> Remove multicall contract requirement

app/ts/background/windows/confirmTransaction.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
if we are in signing mode, don't make any address rich
=> make micah poor again

app/ts/background/settings.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1109
=> geth -> ethereum

app/ts/background/metadataUtils.ts, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/simulationExplaining/customExplainers/ProxySendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleSendVisualisations.tsx, app/ts/components/simulationExplaining/customExplainers/SimpleTokenApprovalVisualisation.tsx, app/ts/components/subcomponents/InlineCard.tsx, app/ts/components/subcomponents/coins.tsx
- Fix invisible ether when hovered
- Make ether not copyable/editable
- refactor <EtherSymbol to be just TokenSymbol
=> fix invisible ether, fix copyable/editable ether, refactor<EtherSymbol

app/css/interceptor.css, app/ts/components/subcomponents/coins.tsx
Buttons maintain size while text and symbol size can be dynamically set
https://github.com/user-attachments/assets/2866c44a-737b-4293-a46e-fd8238a00d61
=> Detached font sizing for buttons on token symbol

app/css/interceptor.css, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/simulationExplaining/Transactions.tsx, app/ts/components/subcomponents/Error.tsx
- there's mixed uses of paddings and margins for errors. This PR separates them by margin only so the margins get merged together
- allow importance box to be smaller than 400px on small window
=> merge margins together (instead of mixing paddings and margings), allow importance box to scale smaller

app/ts/types/ethSimulate-types.ts
I reported this to Sina, but this is the fix for now
=> blockhash can be null for logs at times for logs for base

app/ts/background/background-startup.ts, app/ts/background/backgroundUtils.ts, app/ts/components/App.tsx, app/ts/components/pages/AddNewAddress.tsx, app/ts/components/pages/ChangeChain.tsx, app/ts/components/pages/ConfirmTransaction.tsx, app/ts/components/pages/InterceptorAccess.tsx, app/ts/components/pages/SettingsView.tsx, app/ts/components/pages/WebsiteAccess.tsx, app/ts/components/simulationExplaining/customExplainers/GnosisSafeVisualizer.tsx, app/ts/components/simulationExplaining/customExplainers/GovernanceVoteVisualizer.tsx
apparently you shouldn't have async message listeners according to this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage
=> don't add async message listeners

app/css/bulma.css
=> make transaction input background transparent. It never makes sense to have default color of white

app/ts/utils/contentScriptsUpdating.ts
- now on manifest v3 we are injecting to all sub pages
- on manifest v2 if interceptor is disabled for one domain on the site, disable the whole tab
=> interceptor disabling

app/ts/components/simulationExplaining/customExplainers/CatchAllVisualizer.tsx, app/ts/components/simulationExplaining/identifyTransaction.tsx, app/ts/components/ui-utils.tsx
=> support multiple own accounts at the same time in the importance view

app/ts/components/pages/Home.tsx
fix https://github.com/DarkFlorist/TheInterceptor/issues/1250
=> make isEmpty more accurate

app/ts/background/simulationModeHanders.ts, app/ts/simulation/SimulationStackExtraction.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts
just move functions to another file
=> remove stack extraction methods from the simulation ethereum client

app/ts/background/simulationUpdating.ts, app/ts/components/pages/Home.tsx, app/ts/components/pages/PersonalSign.tsx, app/ts/components/simulationExplaining/customExplainers/EnsEventExplainer.tsx, app/ts/components/ui-utils.tsx, app/ts/simulation/compoundGovernanceFaking.ts, app/ts/simulation/services/EthereumClientService.ts, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/utils/bigint.ts
fix https://github.com/DarkFlorist/TheInterceptor/issues/1257
=> add bigintSecondsToDate and dateToBigintSeconds

app/ts/background/background.ts
- fix bug that failing transactions were not shown
- fix bug that we were picking undefined ABI's instead of non-undefined ones for error parsing
=> parse failing transactions

app/ts/components/subcomponents/TimePicker.tsx, app/ts/simulation/services/SimulationModeEthereumClientService.ts, app/ts/types/visualizer-types.ts
=> Add months to time picker

app/inpage/ts/listenContentScript.ts
check that messages are interceptor requests and only then forward to interceptor
=> forward only interceptor requests to interceptor

app/ts/background/metadataUtils.ts
there's a bug that we are trying to look for addresses that are actually array of addresses.
=> get flat list of addresses
